--- CHANGE CONTEXT TO NEW DATABASE
USE NH_MTN_DB
GO
--- SELECT ALL MOUNTAINS ORDERED BY HIGHEST ELEVATION
SELECT        *
FROM        Peaks
ORDER        BY elevation DESC
GO
--- SELECT ALL MOUNTAINS ORDERED BY NAME
SELECT        *
FROM        Peaks
ORDER        BY mountain ASC
GO
--- SELECT MOUNTAINS WHERE ELEVATION BETWEEN 5000 AND 6500' and ORDERED BY ELEVATION
SELECT        *
FROM        Peaks
WHERE        elevation BETWEEN 5000 AND 6500
ORDER        BY elevation DESC
GO
